Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Travel2.Models.Domain;

namespace Travel2.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
       private readonly DatabaseContext _databaseContext;
            public AdminController(DatabaseContext databaseContext)
            {
                _databaseContext = databaseContext;
            }
            [HttpGet]
            public async Task<IActionResult> Display()
            {
            var book = await _databaseContext.Tours.ToListAsync();
            return View(book);
            }
            [HttpGet]
            public async Task<IActionResult> Delete(int id)
            {
                var book = await _databaseContext.Tours.FindAsync(id);
                if (book == null)
                {
                    return NotFound();
                }
                    _databaseContext.Tours.Remove(book);
                    await _databaseContext.SaveChangesAsync();
                return RedirectToAction("Display");
            }
    }
}

Controllers/UserAuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Travel2.Models.DTO;
using Travel2.Repositories.Abstract;

namespace Travel2.Controllers
{
    public class UserAuthenticationController : Controller
    {
            
        private readonly IUserAuthenticationService _authService;
        public UserAuthenticationController(IUserAuthenticationService authService)
        {
            this._authService = authService;
        }


        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(Login model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await _authService.LoginAsync(model);
            if (result.StatusCode == 1)
            {
                return RedirectToAction("Display", "Admin");
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(Registration model)
        {
            if (!ModelState.IsValid) { return View(model); }
            model.Role = "user";
            var result = await this._authService.RegisterAsync(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this._authService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }
        //public async Task<IActionResult> RegisterAdmin()
        //{
        //    Registration model = new Registration
        //    {
        //        Username = "admin",
        //        Name = "Kani",
        //        Email = "admin@gmail.com",
        //        Password = "Admin@12345#"
        //    };
        //    model.Role = "admin";
        //    var result = await this._authService.RegisterAsync(model);
        //    return Ok(result);
        //}

        [Authorize]
        public IActionResult ChangePassword()
        {
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Wanderlust - Home</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="" rel="icon">
  <link href="~/images/wanderlust (1).png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
    rel="stylesheet">
  <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/vendor/aos/aos.css" rel="stylesheet">
  <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="~/css/variables.css" rel="stylesheet">
  <link href="~/css/main.css" rel="stylesheet">

</head>
<body>
  <header id="header" class="header fixed-top" data-scrollto-offset="0" style="height: 100px;">
    <div class="container-fluid d-flex align-items-center justify-content-between">
      <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
        <img src="~/images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a casp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
          <li class="dropdown"><a asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="services"><span>Tours</span> <i
                class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a asp-area="" asp-controller="Home" asp-action="BikeTours">Bike tours</a></li>
              <li><a asp-area="" asp-controller="Home" asp-action="CentralAsiaTours">Central Asia tours</a></li>
              <li><a asp-area="" asp-controller="Home" asp-action="HorsebackTours">Horseback tours</a></li>
              <li><a asp-area="" asp-controller="Home" asp-action="OneDayTours">One day tours</a></li>
              <li><a asp-area="" asp-controller="Home" asp-action="Trekking">Trekking in Kyrgyzstan</a></li>
            </ul>
          </li>
          <li><a asp-area="" asp-controller="Home" asp-action="Blog">Blog</a></li>
          <li class="dropdown"><a href="#"><span>Kyrgyzstan</span> <i
                class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a asp-area="" asp-controller="Home" asp-action="AboutKyrgyzstan">About Kyrgyzstan</a></li>
              <li><a asp-area="" asp-controller="Home" asp-action="Sights">Sights</a></li>
            </ul>
          </li>
          <li><a asp-area="" asp-controller="Home" asp-action="PhotoGallery">Photo gallery</a></li>
          <li><a  asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="about">About us</a></li>
          <li><a asp-area="" asp-controller="UserAuthentication" asp-action="Login" class="login"><i class="bi bi-person-circle"></i></a></li>
           @if (User.IsInRole("admin"))
                {
                    <li><a asp-area="" asp-controller="Admin" asp-action="Display"></a></li>
                }

        </ul>
      </nav><!-- .navbar -->
    </div>
  </header>


    
    <div class="container">
         @RenderBody()
    </div>

   <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="~/images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
              </a>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <p>
              Wanderlust<br><br>
              <strong>Phone:</strong> +996 777 22 12 02<br>
              <strong>Email:</strong> kanysh150@gmail.com<br>
            </p>
          </div>



          <div class="col-lg-4 col-md-6 footer-newsletter">
            <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="https://www.facebook.com/profile.php?id=100037099418214" class="facebook"><i
                  class="bi bi-facebook"></i></a>
              <a href="https://www.instagram.com/___karataeva/" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="https://twitter.com/kanykei__kg?t=RK8ip_mhHiBfAP6gv6QgCQ&s=09" class="google-plus"><i
                  class="bi bi-telegram"></i></a>
              <a href="https://wa.me/996777221201" class="linkedin"><i class="bi bi-whatsapp"></i></a>
            </div>

          </div>

        </div>
      </div>
    </div>


  </footer><!-- End Footer -->
      <!-- Vendor JS Files -->
  <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/vendor/aos/aos.js"></script>
  <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="~/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/vendor/email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/js/main.js"></script>
</body>
</html>