Models/Tour.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Travel2.Models
{
    public class Tour
    { 
        [Key]
        public int Id { get; set; }
        public string? UserName { get; set; }
        [Required]
        public string? Usermail { get; set; }
        [Required]
        public string? PhoneNumber { get; set; }
        public string? TypeOfTour { get; set; }
        public string? Message { get; set; }
        public DateTime? DateOfTour { get; set; }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Travel2.Models;
using Travel2.Models.Domain;

namespace Travel2.Controllers
{
    public class DashboardController : Controller
    {
        private readonly DatabaseContext _databaseContext;
        public DashboardController(DatabaseContext databaseContext)
        {
                _databaseContext = databaseContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Book bookRequest)
        {
            var book = new Tour()
            {
                UserName = bookRequest.UserName,
                Usermail = bookRequest.Usermail,
                PhoneNumber = bookRequest.PhoneNumber,
                TypeOfTour = bookRequest.TypeOfTour,
                Message = bookRequest.Message,
                DateOfTour = bookRequest.DateOfTour
            };

           await _databaseContext.Tours.AddAsync(book);
           await _databaseContext.SaveChangesAsync();
            TempData["success"] = "Added successfully!!!";
            return RedirectToAction("Add");

        }

    }
}

Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;

namespace Travel2.Controllers
{
    public class TourController : Controller
    {
        public IActionResult Biketour1()
        {
            return View();
        }
        public IActionResult CentralAsia1()
        {
            return View();
        }
        public IActionResult Trekking1()
        {
            return View();
        }
        public IActionResult OneDayTour3()
        {
            return View();
        }
        public IActionResult OneDayTour5()
        {
            return View();
        }
        public IActionResult HorsebackTour1()
        {
            return View();
        }
        public IActionResult OneDayTour1()
        {
            return View();
        }
        public IActionResult OneDayTour2()
        {
            return View();
        }
        public IActionResult OneDayTour4()
        {
            return View();
        }
        public IActionResult OneDayTour6()
        {
            return View();
        }
        public IActionResult Trekking2()
        {
            return View();
        }
        public IActionResult Trekking3()
        {
            return View();
        }
    }
}

Views/Tour/Biketour1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

@*<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Wanderlust - Bike Tours</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="images/wanderlust (1).png" rel="icon">
    <link href="images/wanderlust (1).png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="assets/css/variables.css" rel="stylesheet">
    <link href="assets/css/main.css" rel="stylesheet">

</head>*@

<body>

    <!-- ======= Header ======= -->
    @*<header id="header" class="header fixed-top" data-scrollto-offset="0" style="height: 100px;">
        <div class="container-fluid d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" href="index.html">Home</a></li>
                    <li class="dropdown"><a href="index.html#services"><span>Tours</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="bikeTours.html">Bike tours</a></li>
                            <li><a href="centralAsiaTours.html">Central Asia tours</a></li>
                            <li><a href="houseBackTours.html">Horseback tours</a></li>
                            <li><a href="oneDayTours.html">One day tours</a></li>
                            <li><a href="trekkingInKyrgyzstan.html">Trekking in Kyrgyzstan</a></li>
                        </ul>
                    </li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown"><a href=""><span>Kyrgyzstan</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="aboutKyrgyzstan.html">About Kyrgyzstan</a></li>
                            <li><a href="sights.html">Sights</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="photoGallery.html">Photo gallery</a></li>
                    <li><a class="nav-link scrollto" href="aboutUs.html">About us</a></li>
                    <li><a href="#" class="login"><i class="bi bi-person-circle"></i></a></li>
                </ul>
            </nav><!-- .navbar -->
        </div>
    </header>*@<!-- End Header -->

    <section id="hero-animated" class="hero-animated d-flex align-items-center">
        <div class="container d-flex flex-column justify-content-center align-items-center text-center position-relative"
            data-aos="zoom-out">
            <img src="~/images/bike1.jpg" class="img-fluid animated">
            <h3>Biking in Kyrgyzstan – vast mountain ranges and windy roads want to be explored!</h3>
        </div>
    </section>

    <main id="main">
        <section id="cta" class="cta">
            <div class="container" data-aos="zoom-out">

                <div class="row g-5">

                    <div
                        class="col-lg-8 col-md-6 content d-flex flex-column justify-content-center order-last order-md-first">
                    
                        <p>Old ruins from the era of the Great Silk Road, deep lakes and spacious views of the massive
                            mountains, herds of free horses on the slopes, mineral springs and culture of the nomadic
                            people – all this are on Kyrgyz land.Choose a tour – walking, cycling or equestrian and find
                            adventures with “Wanderlust” – your travel agency for active recreation!</p>
                        <p>MTB tours are going to be very popular in Kyrgyzstan and for your attention we offer real,
                            challenging mountain bike trail tours for advanced bike riders.</p>

                    </div>

                    <div class="col-lg-4 col-md-6 order-first order-md-last d-flex align-items-center">
                        <div class="img">
                            <img src="~/images/bike3.jpg" alt="" class="img-fluid">
                        </div>
                    </div>

                </div>

            </div>
        </section>
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="row g-4 g-lg-5" data-aos="fade-up" data-aos-delay="200">

                    <div class="col-lg-5">
                        <div class="about-img">
                            <img src="~/images/bike5.jpg" class="img-fluid" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7">
                        <!-- Tabs -->
                        <ul class="nav nav-pills mb-3">
                            <li><a class="nav-link active" data-bs-toggle="pill" href="#tab1"></a>
                            </li>
                        </ul><!-- End Tabs -->

                        <!-- Tab Content -->
                        <div class="tab-content">

                            <div class="tab-pane fade show active" id="tab1">

                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Itinerary: Bishkek – Kegety – Songkul – Baetova – Tashrabat – Chatyrkul – KelSuu
                                        – Aksay valley – Naryn – Tosor – Karakol – Tamchy – Chongkemin – Bishkek.</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Duration: 13 days</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Best Season: Mid June – September</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Level of Difficulty: Difficult</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Tour cost: 7000 som</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Group Size: 4-12 pax</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Requirements: weatherproof warm clothes, trekking boots, hat, sunglasses,
                                        sleeping bag, and sunscreen.</h4>
                                </div>

                            </div><!-- End Tab 1 Content -->
                        </div>
                    </div>
                </div>
            </div>
        </section>

       <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <a asp-area="" asp-controller="Dashboard" asp-action="Add" class="email-form">
        <div class="text-center"><button type="submit">Book tour</button></div>
      </a>
    </section><!-- End Contact Section -->

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
@*    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                                <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
                            </a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <p>
                            Wanderlust<br><br>
                            <strong>Phone:</strong> +996 777 22 12 02<br>
                            <strong>Email:</strong> kanysh150@gmail.com<br>
                        </p>
                    </div>



                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="https://www.facebook.com/profile.php?id=100037099418214" class="facebook"><i
                                    class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com/___karataeva/" class="instagram"><i
                                    class="bi bi-instagram"></i></a>
                            <a href="https://twitter.com/kanykei__kg?t=RK8ip_mhHiBfAP6gv6QgCQ&s=09"
                                class="google-plus"><i class="bi bi-telegram"></i></a>
                            <a href="https://wa.me/996777221201" class="linkedin"><i class="bi bi-whatsapp"></i></a>
                        </div>

                    </div>

                </div>
            </div>
        </div>


    </footer><!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="assets/vendor/email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>*@

</body>

</html>

Views/Tour/CentralAsia1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

@*<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Wanderlust - Central Asia tours</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="images/wanderlust (1).png" rel="icon">
    <link href="images/wanderlust (1).png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="assets/css/variables.css" rel="stylesheet">
    <link href="assets/css/main.css" rel="stylesheet">

</head>*@

<body>

@*    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top" data-scrollto-offset="0" style="height: 100px;">
        <div class="container-fluid d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" href="index.html">Home</a></li>
                    <li class="dropdown"><a href="index.html#services"><span>Tours</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="bikeTours.html">Bike tours</a></li>
                            <li><a href="centralAsiaTours.html">Central Asia tours</a></li>
                            <li><a href="houseBackTours.html">Horseback tours</a></li>
                            <li><a href="oneDayTours.html">One day tours</a></li>
                            <li><a href="trekkingInKyrgyzstan.html">Trekking in Kyrgyzstan</a></li>
                        </ul>
                    </li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown"><a href=""><span>Kyrgyzstan</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="aboutKyrgyzstan.html">About Kyrgyzstan</a></li>
                            <li><a href="sights.html">Sights</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="photoGallery.html">Photo gallery</a></li>
                    <li><a class="nav-link scrollto" href="aboutUs.html">About us</a></li>
                    <li><a href="#" class="login"><i class="bi bi-person-circle"></i></a></li>
                </ul>
            </nav><!-- .navbar -->
        </div>
    </header><!-- End Header -->*@

    <section id="hero-animated" class="hero-animated d-flex align-items-center">
        <div class="container d-flex flex-column justify-content-center align-items-center text-center position-relative"
            data-aos="zoom-out">
            <img src="~/images/centralAsiaTours2.jpg" class="img-fluid animated">
            <h3>Uzbekistan</h3>
        </div>
    </section>

    <main id="main">
        <section id="cta" class="cta">
            <div class="container" data-aos="zoom-out">

                <div class="row g-5">

                    <div
                        class="col-lg-8 col-md-6 content d-flex flex-column justify-content-center order-last order-md-first">

                        <p>It is surrounded by five landlocked countries: Kazakhstan to the north; Kyrgyzstan to the
                            northeast; Tajikistan to the southeast; Afghanistan to the south; and Turkmenistan to the
                            southwest. Its capital and largest city is Tashkent. Uzbekistan is part of the Turkic world,
                            as well as a member of the Organization of Turkic States. The Uzbek language is the
                            majority-spoken language in Uzbekistan, while Russian is widely spoken and understood
                            throughout the country. Tajik is also spoken as a minority language, predominantly in
                            Samarkand and Bukhara. Islam is the predominant religion in Uzbekistan, most Uzbeks being
                            Sunni Muslims.
                        </p>
                        <p>The first recorded settlers in what is now Uzbekistan were Eastern Iranian nomads, known as
                            Scythians, who founded kingdoms in Khwarazm (8th–6th centuries BC), Bactria (8th–6th
                            centuries BC), Sogdia (8th–6th centuries BC), Fergana (3rd century BC – sixth century AD),
                            and Margiana (3rd century BC – sixth century AD).[18] The area was incorporated into the
                            Iranian Achaemenid Empire and, after a period of Macedonian rule, was ruled by the Iranian
                            Parthian Empire and later by the Sasanian Empire, until the Muslim conquest of Persia in the
                            seventh century.</p>
                    </div>

                    <div class="col-lg-4 col-md-6 order-first order-md-last d-flex align-items-center">
                        <div class="img">
                            <img src="/~/images/centralAsiaTours.jpg" alt="" class="img-fluid">
                        </div>
                    </div>

                </div>

            </div>
        </section>
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="row g-4 g-lg-5" data-aos="fade-up" data-aos-delay="200">

                    <div class="col-lg-5">
                        <div class="about-img">
                            <img src="~/images/centralAsiaTours1.jpg" class="img-fluid" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7">
                        <!-- Tabs -->
                        <ul class="nav nav-pills mb-3">
                            <li><a class="nav-link active" data-bs-toggle="pill" href="#tab1"></a>
                            </li>
                        </ul><!-- End Tabs -->

                        <!-- Tab Content -->
                        <div class="tab-content">

                            <div class="tab-pane fade show active" id="tab1">

                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Itinerary: Bishkek – Tashkent - Urgench - Khiva - Bukhara - Samarkand - Tashkent
                                        - Andijan - Osh - Bishkek</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Duration: 14 days</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Best Season: all year round</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Level of Difficulty: Difficulty</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Tour cost: 30000 som</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Group Size: 2-20 pax</h4>
                                </div>
                                <div class="d-flex align-items-center mt-4">
                                    <i class="bi bi-dot"></i>
                                    <h4>Requirements: weatherproof warm clothes, trekking boots, hat, sunglasses,
                                        sleeping bag, and sunscreen.</h4>
                                </div>

                            </div><!-- End Tab 1 Content -->
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <a asp-area="" asp-controller="Dashboard" asp-action="Add" class="email-form">
        <div class="text-center"><button type="submit">Book tour</button></div>
      </a>
    </section><!-- End Contact Section -->

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
@*    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                                <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
                            </a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <p>
                            Wanderlust<br><br>
                            <strong>Phone:</strong> +996 777 22 12 02<br>
                            <strong>Email:</strong> kanysh150@gmail.com<br>
                        </p>
                    </div>



                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="https://www.facebook.com/profile.php?id=100037099418214" class="facebook"><i
                                    class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com/___karataeva/" class="instagram"><i
                                    class="bi bi-instagram"></i></a>
                            <a href="https://twitter.com/kanykei__kg?t=RK8ip_mhHiBfAP6gv6QgCQ&s=09"
                                class="google-plus"><i class="bi bi-telegram"></i></a>
                            <a href="https://wa.me/996777221201" class="linkedin"><i class="bi bi-whatsapp"></i></a>
                        </div>

                    </div>

                </div>
            </div>
        </div>


    </footer><!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="assets/vendor/email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>*@

</body>

</html>