Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Travel2.Models;

namespace Travel2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult AboutKyrgyzstan()
        {
            return View();
        }
        public IActionResult BikeTours()
        {
            return View();
        }
        public IActionResult CentralAsiaTours()
        {
            return View();
        }
        public IActionResult HorsebackTours()
        {
            return View();
        }
        public IActionResult OneDayTours()
        {
            return View();
        }
        public IActionResult Trekking()
        {
            return View();
        }
        public IActionResult Sights()
        {
            return View();
        }
        public IActionResult Blog()
        {
            return View();
        }
        public IActionResult PhotoGallery()
        {
            return View();
        }
        
       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SightsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Travel2.Controllers
{
    public class SightsController : Controller
    {
        public IActionResult Arstanbob()
        {
            return View();
        }
        public IActionResult SaimaluuTash()
        {
            return View();
        }
         public IActionResult Batken()
        {
            return View();
        }
        public IActionResult Jalalabad()
        {
            return View();
        }
        public IActionResult Issykkol()
        {
            return View();
        }
        public IActionResult Songkol()
        {
            return View();
        }
        public IActionResult Tashrabat()
        {
            return View();
        }
        public IActionResult Osh()
        {
            return View();
        }
        public IActionResult Kelsuu()
        {
            return View();
        }
        public IActionResult Bishkek()
        {
            return View();
        }
        public IActionResult Talas()
        {
            return View();
        }
        public IActionResult Sarychelek()
        {
            return View();
        }
    }
}

Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;

namespace Travel2.Controllers
{
    public class TourController : Controller
    {
        public IActionResult Biketour1()
        {
            return View();
        }
        public IActionResult CentralAsia1()
        {
            return View();
        }
        public IActionResult Trekking1()
        {
            return View();
        }
        public IActionResult OneDayTour3()
        {
            return View();
        }
        public IActionResult OneDayTour5()
        {
            return View();
        }
        public IActionResult HorsebackTour1()
        {
            return View();
        }
        public IActionResult OneDayTour1()
        {
            return View();
        }
        public IActionResult OneDayTour2()
        {
            return View();
        }
        public IActionResult OneDayTour4()
        {
            return View();
        }
        public IActionResult OneDayTour6()
        {
            return View();
        }
        public IActionResult Trekking2()
        {
            return View();
        }
        public IActionResult Trekking3()
        {
            return View();
        }
    }
}

Views/Home/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/BikeTours.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

@*<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Wanderlust - Bike Tours</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="images/wanderlust (1).png" rel="icon">
  <link href="images/wanderlust (1).png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <link href="assets/css/variables.css" rel="stylesheet">

  <link href="assets/css/main.css" rel="stylesheet">

</head>*@

<body>

  <!-- ======= Header ======= -->
@*  <header id="header" class="header fixed-top" data-scrollto-offset="0" style="height: 100px;">
    <div class="container-fluid d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
        <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto" href="index.html">Home</a></li>
          <li class="dropdown"><a href="index.html#services"><span>Tours</span> <i
                class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="bikeTours.html">Bike tours</a></li>
              <li><a href="centralAsiaTours.html">Central Asia tours</a></li>
              <li><a href="houseBackTours.html">Horseback tours</a></li>
              <li><a href="oneDayTours.html">One day tours</a></li>
              <li><a href="trekkingInKyrgyzstan.html">Trekking in Kyrgyzstan</a></li>
            </ul>
          </li>
          <li><a href="blog.html">Blog</a></li>
          <li class="dropdown"><a href=""><span>Kyrgyzstan</span> <i
                class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="aboutKyrgyzstan.html">About Kyrgyzstan</a></li>
              <li><a href="sights.html">Sights</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="photoGallery.html">Photo gallery</a></li>
          <li><a class="nav-link scrollto" href="aboutUs.html">About us</a></li>
          <li><a href="#" class="login"><i class="bi bi-person-circle"></i></a></li>
        </ul>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->*@

  <section id="hero-fullscreen" class="hero-fullscreen d-flex align-items-center"
    style="background: url(/images/bike3.jpg);">
    <div class="container d-flex flex-column align-items-center position-relative" data-aos="zoom-out">
      <h2>Bike tours</h2>
      <p>Cycling can be an enjoyable experience in Kyrgyzstan.</p>
      <p>Thanks to the hard work of Kyrgyz government, a lot of bicycle tracks have been built in Bishkek since 2019.
      </p>
      <p>Now you can explore this historical city not only on foot, but also by your bike!</p>
    </div>
  </section>

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row g-4 g-lg-5" data-aos="fade-up" data-aos-delay="200">

          <div class="col-lg-5">
            <div class="about-img">
              <img src="~/images/bike5.jpg" class="img-fluid" alt="">
            </div>
          </div>

          <div class="col-lg-7">
            <!-- Tabs -->
            <ul class="nav nav-pills mb-3">
              <li><a class="nav-link active" data-bs-toggle="pill" href="#tab1"></a></li>
            </ul><!-- End Tabs -->

            <!-- Tab Content -->
            <div class="tab-content">

              <div class="tab-pane fade show active" id="tab1">

                <p class="fst-italic">Do you know that Kyrgyzstan is the country with the most preserved nature in
                  Central Asia? That there are high peaks up to 7 400m above sea level and massive mountain range
                  Tien-Shan. What her vast forests abound wild animals? Do you know that among its secret gorges and on
                  mountain ranges lurched nomadic villages and mountainous crystal lakes hid, that life their flows with
                  its natural, traditional, calm rhythm, and people meet a stranger as a dear guest?
                  This is Kyrgyzstan. Not the one with massive advertisements that tempt all-inclusive hotel comfort at
                  resorts. Not the one that runs through the crowded streets of the XXI century. This is another world.
                  Kyrgyzstan expects you to put a backpack on your back, ride a bicycle or a horse and explore its
                  unexplored corners.
                  Old ruins from the era of the Great Silk Road, deep lakes and spacious views of massive mountains,
                  herds of free horses on the slopes, mineral springs and culture of the nomadic people — all this is on
                  Kyrgyz land.
                  Choose a tour — walking, cycling, equestrian and find adventures with “Wanderlust” — your travel
                  agency for active recreation!

                  The MTB tour is going to be very popular in Kyrgyzstan and for your attention we offer real challenge
                  mountain bike trail tours for advanced bike riders.</p>
              </div><!-- End Tab 1 Content -->
            </div>
          </div>
        </div>
      </div>
    </section><!-- End About Section -->

    <section id="services" class="services">
      <div class="container" data-aos="fade-up">


        <div class="row gy-5">

          <div class="col-xl-4 col-md-6" data-aos="zoom-in" data-aos-delay="300">
            <div class="service-item">
              <div class="img">
                <img src="~/images/bike1.jpg  " class="img-fluid" alt="">
              </div>
              <div class="details position-relative">
                <a asp-area="" asp-controller="Tour" asp-action="Biketour1" class="stretched-link">
                  <h3>Mountain Bike Tour Pro</h3>
                </a> </div>
            </div>
          </div><!-- End Service Item -->


        </div>

      </div>
    </section>

  </main><!-- End #main -->

@*  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="~images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
              </a>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <p>
              Wanderlust<br><br>
              <strong>Phone:</strong> +996 777 22 12 02<br>
              <strong>Email:</strong> kanysh150@gmail.com<br>
            </p>
          </div>



          <div class="col-lg-4 col-md-6 footer-newsletter">
            <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="https://www.facebook.com/profile.php?id=100037099418214" class="facebook"><i
                  class="bi bi-facebook"></i></a>
              <a href="https://www.instagram.com/___karataeva/" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="https://twitter.com/kanykei__kg?t=RK8ip_mhHiBfAP6gv6QgCQ&s=09" class="google-plus"><i
                  class="bi bi-telegram"></i></a>
              <a href="https://wa.me/996777221201" class="linkedin"><i class="bi bi-whatsapp"></i></a>
            </div>

          </div>

        </div>
      </div>
    </div>


  </footer><!-- End Footer -->*@

@*  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>*@

</body>

</html>

Views/Home/CentralAsiaTours.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">

@*<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Wanderlust - Central Asia tours</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="images/wanderlust (1).png" rel="icon">
    <link href="images/wanderlust (1).png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="assets/css/variables.css" rel="stylesheet">

    <link href="assets/css/main.css" rel="stylesheet">

</head>*@

<body>

    <!-- ======= Header ======= -->
    @*<header id="header" class="header fixed-top" data-scrollto-offset="0" style="height: 100px;">
        <div class="container-fluid d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" href="index.html">Home</a></li>
                    <li class="dropdown"><a href="index.html#services"><span>Tours</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="bikeTours.html">Bike tours</a></li>
                            <li><a href="centralAsiaTours.html">Central Asia tours</a></li>
                            <li><a href="houseBackTours.html">Horseback tours</a></li>
                            <li><a href="oneDayTours.html">One day tours</a></li>
                            <li><a href="trekkingInKyrgyzstan.html">Trekking in Kyrgyzstan</a></li>
                        </ul>
                    </li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown"><a href=""><span>Kyrgyzstan</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="aboutKyrgyzstan.html">About Kyrgyzstan</a></li>
                            <li><a href="sights.html">Sights</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="photoGallery.html">Photo gallery</a></li>
                    <li><a class="nav-link scrollto" href="aboutUs.html">About us</a></li>
                    <li><a href="#" class="login"><i class="bi bi-person-circle"></i></a></li>
                </ul>
            </nav><!-- .navbar -->
        </div>
    </header><!--*@ End Header -->

    <section id="hero-fullscreen" class="hero-fullscreen d-flex align-items-center"
        style="background: url(/images/centralAsiaTours.jpg);">
        <div class="container d-flex flex-column align-items-center position-relative" data-aos="zoom-out">
            <h2>Central Asia tours</h2>
            <p>Create unforgettable memories with Central Asia tours</p>
        </div>
    </section>

    <main id="main">

        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">

                <div class="row g-4 g-lg-5" data-aos="fade-up" data-aos-delay="200">

                    <div class="col-lg-5">
                        <div class="about-img">
                            <img src="~/images/centralAsiaTours1.jpg" class="img-fluid" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7">
                        <!-- Tabs -->
                        <ul class="nav nav-pills mb-3">
                            <li><a class="nav-link active" data-bs-toggle="pill" href="#tab1"></a></li>
                        </ul><!-- End Tabs -->

                        <!-- Tab Content -->
                        <div class="tab-content">

                            <div class="tab-pane fade show active" id="tab1">

                                <p class="fst-italic">Central Asia is a gigantic land with rich history and fascinating
                                    nature. Here steppes meet mountains, and ancient cities meet the modern age. Central
                                    Asia is famous for the Great Silk Road that connected Asia and Europe. The Pamir
                                    Mountains of Tajikistan, deserts of Turkmenistan and Uzbekistan, and lakes of
                                    Kyrgyzstan decorate it, bringing a special feature of such a long way. The heritage
                                    of these times is well-preserved and attracts travelers to visit Central Asia.</p>
                                <p class="fst-italic">Taking a trip to Central Asia, tourists visit such great places
                                    as:</p>
                                <p class="fst-italic"><i class="bi bi-dot"></i>Kyrgyzstan, Uzbekistan, Kazakhstan,
                                    Tajikistan</p>
                                <p class="fst-italic">Although all these countries are historically connected, they are
                                    pretty diverse and each of them deserves attention.</p>
                                <p class="fst-italic">Why It Is Worth to Travel to Central Asia
                                    Central Asia tourism is a great choice to have a great trip full of beautiful sights
                                    and enlightening content. The coverage of countries and places to visit is quite
                                    large. Let’s figure out what makes it so interesting and worth trying:</p>
                            </div><!-- End Tab 1 Content -->
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End About Section -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
            <div class="container" data-aos="fade-up">

                <div class="section-header">
                    <h2>Tour type</h2>
                </div>

                <div class="row gy-5">

                    <div class="col-xl-4 col-md-6" data-aos="zoom-in" data-aos-delay="200">
                        <div class="service-item">
                            <div class="img">
                                <img src="~/images/trekking1.jpg" class="img-fluid" alt="">
                            </div>
                            <div class="details position-relative">

                                <a asp-area="" asp-controller="Tour" asp-action="Trekking1" class="stretched-link">
                                    <h3>Alay Heights</h3>
                                </a>
                                <p>The nature park is named after the river Ala-Archa which flows through it</p>
                            </div>
                        </div>
                    </div><!-- End Service Item -->

                    <div class="col-xl-4 col-md-6" data-aos="zoom-in" data-aos-delay="300">
                        <div class="service-item">
                            <div class="img">
                                <img src="~/images/centralAsiaTours2.jpg" class="img-fluid" alt="">
                            </div>
                            <div class="details position-relative">
                                <a asp-area="" asp-controller="Tour" asp-action="CentralAsia1" class="stretched-link">
                                    <h3>Uzbekistan</h3>
                                </a>
                                <p>Uzbekistan is a doubly landlocked country located in Central Asia</p>
                            </div>
                        </div>
                    </div><!-- End Service Item -->

                    <div class="col-xl-4 col-md-6" data-aos="zoom-in" data-aos-delay="400">
                        <div class="service-item">
                            <div class="img">
                                <img src="~/images/oneDayTours3.jpg" class="img-fluid" alt="">
                            </div>
                            <div class="details position-relative">
                                <a hasp-area="" asp-controller="Tour" asp-action="OneDayTour3" class="stretched-link">
                                    <h3>Almaty</h3>
                                </a>
                                <p>Almaty is the largest city in Kazakhstan</p>
                            </div>
                        </div>
                    </div><!-- End Service Item -->

                </div>

            </div>
        </section><!-- End Services Section -->
    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
  @*  <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <a href="index.html" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                                <img src="~/images/wanderlust (1).png" alt="Main Page" class="rounded-pill">
                            </a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <p>
                            Wanderlust<br><br>
                            <strong>Phone:</strong> +996 777 22 12 02<br>
                            <strong>Email:</strong> kanysh150@gmail.com<br>
                        </p>
                    </div>



                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="https://www.facebook.com/profile.php?id=100037099418214" class="facebook"><i
                                    class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com/___karataeva/" class="instagram"><i
                                    class="bi bi-instagram"></i></a>
                            <a href="https://twitter.com/kanykei__kg?t=RK8ip_mhHiBfAP6gv6QgCQ&s=09"
                                class="google-plus"><i class="bi bi-telegram"></i></a>
                            <a href="https://wa.me/996777221201" class="linkedin"><i class="bi bi-whatsapp"></i></a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
*@

  @*  </footer><!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="assets/vendor/email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>*@

</body>

</html>